### ISSUE TITLE
make `emitDiagnostic` sync (not async)

### ISSUE THREAD

**Issue by yoav-steinberg** [Chriscbr/codespan-wasm#1]
I don't see why `emitDiagnostic` should be async, as it's basically calling codespan-reporting's underlying sync function.
In my specific case I wanted to call `emitDiagnostic` in a js sync function that's being called back from within a wasm sync call:

js ---> call something in wasm and pass a callback to it ---> calls the js callback from within wasm ---> my sync callback can't call `emitDiagnostic` because it's async.

**Comment by Chriscbr** [comment]
I think it it should be possible, if I recall correctly I was just running into some weird webpack errors when I used a regular import.

**Comment by Chriscbr** [comment]
@yoav-steinberg Fixed in v0.4.0 🎉

**Comment by yoav-steinberg** [comment]
perfect! thanks.
